import React from "react";
import { Card } from "../components/utils/Card";

export const About = () => {
  return (
    <section className="section-about container">
      <h2 className="container-title">
        These are the cool facts
        <br />
        generated by our beloved chatGPT
      </h2>
      <Card/>
    </section>
  );
};
